config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "home#index"

  resources :companies do
    resources :activities
  end

  get 'search', to: 'search#results'

end

app/models/company.rb
class Company < ApplicationRecord
	validates :company_name, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 280}
	# validates :location, presence: true, length: {minimum: 500}

	has_many :activities, dependent: :destroy
	belongs_to :user
end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base

	before_action :authenticate_user!
	load_and_authorize_resource
	
	def index
		@companies = Company.all
	end

	def show
		#the company with the id passed in, is retrieved
		@company = Company.find(params[:id])
	end

	def new
		@company = Company.new
	end

	def edit
		@company = Company.find(params[:id])
	end

	def create
		#the new company's parameters are received from the form and stored
		@company = current_user.companies.build(company_params)

		#if there are no errors save the company
		if @company.save
			#send to the index
			redirect_to @company
		else
			#else present the new form again
			render 'new'
		end
	end

	def update
		@company = Company.find(params[:id])

		if @company.update(company_params)
			redirect_to @company
		else
			render 'edit'
		end
	end

	def destroy
		@company = Company.find(params[:id])
		@company.destroy

		redirect_to companies_path
	end

	private
		def company_params
			#on submission, only the following fields are saved
			params.require(:company).permit(:company_name,:description,:location)
		end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .form-group.row
    = f.label :company_name, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :company_name, class: "form-control"
  .form-group.row
    = f.label :description, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :description, class: "form-control"
  .form-group.row
    = f.label :location, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :location, class: "form-control"
  %br/
  

  .actions
    = f.submit 'Save'

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
.container
  .row
    .col-md-12
      %h1 List of Companies

  .row

    - @companies.each do |company|
      .col-md-6
        .card
          %img.card-img-top{:alt => "Card image cap", :src => "..."}/
          .card-block
            %h4.card-title= company.company_name
            -# %p.card-text= company.description
            = link_to 'Show', company, class: "btn btn-primary"


%br
= link_to 'New Company', new_company_path

-# %table
-#   %thead
-#     %tr
-#       %th
-#       %th
-#       %th
-#
-#   %tbody
-#     - @companies.each do |company|
-#       %tr
-#         %td= company.company_name
-#         %td= link_to 'Show', company
-#         %td= link_to 'Edit', edit_company_path(company)
-#         %td= link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }




%br
=link_to 'Back', root_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice
%br


%h3= @company.company_name
%br

%p= @company.description

%p= @company.location

= link_to 'Edit', edit_company_path(@company)
%br

- if can? :create, @company.activities
  = link_to "New Activity", new_company_activity_path(@company)
  %br
- @company.activities.each do |activity|
  = activity.activity_name
  = link_to "edit", edit_company_activity_path(@company, activity)
  = link_to "view", company_activity_path(@company, activity)
  -# = link_to "edit #{activity.activity_name}", edit_company_activity_path(@company, activity)
  -# = link_to "view #{activity.activity_name}", company_activity_path(@company, activity)
  %br


|
= link_to 'Back', companies_path