config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "home#index"

  resources :companies do
    resources :activities
  end

  get 'search', to: 'search#results'

end

app/models/activity.rb
class Activity < ApplicationRecord
	# validates :activity_name, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 280}
	validates :start_date, presence: true
	validates :end_date, presence: true
	# validates :location, presence: true, length: {minimum: 500}
	validates :mobile, presence: true, numericality: true
	validates :telephone, presence: true, numericality: true

	belongs_to :company
end

app/controllers/activities_controller.rb
class ActivitiesController < InheritedResources::Base

before_action :authenticate_user!
before_action :set_company
load_and_authorize_resource

	def index
		# @activities = @company.activities.all
		redirect_to @company
	end

	def show
		@activity = @company.activities.find(params[:id])
	end

	def new
		@activity = @company.activities.new
	end

	def edit
		@activity =  @company.activities.find(params[:id])
	end

	def create
		@activity =  @company.activities.build(activity_params)

		if @activity.save
			#send to the index
			redirect_to company_activity_path @company, @activity
		else
			#else present the new form again
			render 'new'
		end
	end

	def update
		@activity =  @company.activities.find(params[:id])

		if @activity.update(activity_params)
			redirect_to company_activity_path @company, @activity
		else
			render 'edit'
		end
	end

	def destroy
		@activity = @company.activities.find(params[:id])
		@activity.destroy

		redirect_to  company_activities @company
	end

	private
		def activity_params
			#on submission, only the following fields are saved
			params.require(:activity).permit(:activity_name,:description,:start_date,:end_date,:location,:vehicle,:mobile,:telephone)
		end

		def set_company
			@company = Company.find(params[:company_id])
		end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for @activity, url: company_activities_path(@company), method: :post do |f|
	- if @activity.errors.any?
		#error_explanation
			%h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
			%ul
				- @activity.errors.full_messages.each do |msg|
					%li= msg
  .form-group.row
    = f.label :activity_name, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :activity_name, class: "form-control"
  .form-group.row
    = f.label :description, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :description, class: "form-control"
  .form-group.row
    = f.label :location, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :location, class: "form-control"
	.form-group.row
    = f.label :mobile, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :mobile, class: "form-control"		
	.form-group.row
    = f.label :telephone, class: "col-xs-3 col-form-label"
    .col-xs-9
      = f.text_field :telephone, class: "form-control"

	-# .field
	-# 	= f.label :activity_name
	-# 	%br/
	-# 	= f.text_field :activity_name
	-# .field
	-# 	= f.label :description
	-# 	%br/
	-# 	= f.text_area :description
	.field
		= f.label :start_date
		%br/
		= f.date_select :start_date, default: Date.today, start_year: Date.today.year
	.field
		%br/
		= f.label :end_date
		%br/
		= f.date_select :end_date, default: Date.today, start_year: Date.today.year
	-# .field
	-# 	%br/
	-# 	= f.label :location
	-# 	%br/
	-# 	= f.text_field :location
	.field
		%br/
		= f.label :vehicle
		= f.check_box :vehicle
	.field
		%br/
		= f.label :mobile
		%br/
		= f.text_field :mobile
	.field
		= f.label :telephone
		%br/
		= f.text_field :telephone


	.actions
	%br/
	= f.submit 'Save'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', company_activity_path(@company, @activity)
|
= link_to 'Back', company_activity_path(@company)

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', company_activities_path(@company)

app/views/activities/show.html.haml
%p#notice= notice


= @activity.inspect

= link_to 'Edit', edit_company_activity_path(@company, @activity)
|
= link_to 'Back', company_activities_path(@company)